### ISSUE TITLE
to get ria.json.gz

### ISSUE THREAD

**Issue by vtrokhymenko** [RossiyaSegodnya/ria_news_dataset#3]
hi
how i can get dataset `ria.json.gz`?

**Comment by Ovechkin** [comment]
Hi, you can clone the repository or download by direct url https://github.com/RossiyaSegodnya/ria_news_dataset/raw/master/ria.json.gz

**Comment by vtrokhymenko** [comment]
thx
i have done as you wrote but while i clone at the terminal like `git clone`, file `ria.json.gz` was little size
but when i run your url file downloaded

**Comment by kalaidin** [comment]
Large files are stored with git lfs. Please install it and run `git lfs pull` to get all the files.
